version: '3.8'


services:
  
  backend:
    container_name: backend
    build:
      context: ./src
    ports:
      - "8000:8000"
    depends_on:
      - postgres-db
    env_file:
      - .env
    volumes:
      - static_volume:/usr/src/app/static

  postgres-db:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/static
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  static_volume:
    

