version: '3.8'


services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    env_file:
      - src/.env
  
  backend:
    container_name: backend
    build:
      context: ./src
    ports:
      - "8000:8000"
    depends_on:
      - postgres